main: com.danifoldi.actioncosmetic.ActionCosmeticPlugin
author: DaniFoldi
name: ActionCosmetic
description: Set particle effects for sneaking and jumping
api-version: 1.13
version: ${version}
depend:
  - DataVerse